// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Ballot struct {
	ID          interface{}
	Name        string
	Description string
	Status      string
}

type BallotCandidate struct {
	BallotID    interface{}
	CandidateID interface{}
	Eliminated  bool
}

type Candidate struct {
	ID   interface{}
	Name string
}

type Session struct {
	ID        string
	User      string
	ExpiresAt int64
}

type User struct {
	Email     string
	FirstName string
	LastName  string
}

type Vote struct {
	Email       sql.NullString
	BallotID    interface{}
	CandidateID interface{}
	Rank        int64
}
