// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Ballot struct {
	ID          uuid.UUID
	Name        string
	Description string
	Options     []byte
}

type Session struct {
	ID        string
	User      string
	ExpiresAt int64
}

type User struct {
	Email     string
	FirstName string
	LastName  string
}

type Vote struct {
	ID     uuid.UUID
	Email  string
	Ballot uuid.UUID
	Vote   string
}
