// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
)

type Ballot struct {
	ID          interface{}
	Name        string
	Description string
	Status      string
}

type BallotCandidate struct {
	BallotID    uuid.UUID
	CandidateID uuid.UUID
	Eliminated  bool
}

type Candidate struct {
	ID   interface{}
	Name string
}

type Session struct {
	ID        string
	User      string
	ExpiresAt int64
}

type User struct {
	Email string
	Name  string
}

type Vote struct {
	Email       string
	BallotID    uuid.UUID
	CandidateID uuid.UUID
	Rank        int64
}
