// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addUser = `-- name: AddUser :exec
INSERT OR IGNORE INTO users (
	email, first_name, last_name
) VALUES (
	?, ?, ?
)
`

type AddUserParams struct {
	Email     string
	FirstName string
	LastName  string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser, arg.Email, arg.FirstName, arg.LastName)
	return err
}

const cleanSessions = `-- name: CleanSessions :exec
DELETE FROM sessions WHERE
expires_at < strftime('%s', 'now')
`

func (q *Queries) CleanSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanSessions)
	return err
}

const createBallot = `-- name: CreateBallot :exec
INSERT INTO ballots (
	id, name, description, options
) VALUES (
	?, ?, ?, JSONB(?)
)
`

type CreateBallotParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Jsonb       interface{}
}

func (q *Queries) CreateBallot(ctx context.Context, arg CreateBallotParams) error {
	_, err := q.db.ExecContext(ctx, createBallot,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Jsonb,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
	id, user, expires_at
) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	User      string
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.User, arg.ExpiresAt)
	return err
}

const getBallotVotes = `-- name: GetBallotVotes :many
SELECT id, email, ballot, vote FROM votes
WHERE ballot = ?
`

func (q *Queries) GetBallotVotes(ctx context.Context, ballot uuid.UUID) ([]Vote, error) {
	rows, err := q.db.QueryContext(ctx, getBallotVotes, ballot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Ballot,
			&i.Vote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT user
FROM sessions
WHERE id = ? AND
	  expires_at > strftime('%s', 'now')
`

func (q *Queries) GetSession(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var user string
	err := row.Scan(&user)
	return user, err
}

const submitVote = `-- name: SubmitVote :one
INSERT INTO votes (
	id, email,
	ballot, vote
) VALUES (
	?, ?, ?, ?
) RETURNING id, email, ballot, vote
`

type SubmitVoteParams struct {
	ID     uuid.UUID
	Email  string
	Ballot uuid.UUID
	Vote   string
}

func (q *Queries) SubmitVote(ctx context.Context, arg SubmitVoteParams) (Vote, error) {
	row := q.db.QueryRowContext(ctx, submitVote,
		arg.ID,
		arg.Email,
		arg.Ballot,
		arg.Vote,
	)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Ballot,
		&i.Vote,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT 1 FROM users
WHERE email = ?
`

func (q *Queries) UserExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
