// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addCandidate = `-- name: AddCandidate :exec

INSERT INTO candidates (id, name) VALUES (?, ?)
`

type AddCandidateParams struct {
	ID   interface{}
	Name string
}

// BALLOT SETUP
func (q *Queries) AddCandidate(ctx context.Context, arg AddCandidateParams) error {
	_, err := q.db.ExecContext(ctx, addCandidate, arg.ID, arg.Name)
	return err
}

const addCandidateToBallot = `-- name: AddCandidateToBallot :exec
INSERT INTO ballot_candidates (ballot_id, candidate_id) VALUES (?, ?)
`

type AddCandidateToBallotParams struct {
	BallotID    uuid.UUID
	CandidateID uuid.UUID
}

func (q *Queries) AddCandidateToBallot(ctx context.Context, arg AddCandidateToBallotParams) error {
	_, err := q.db.ExecContext(ctx, addCandidateToBallot, arg.BallotID, arg.CandidateID)
	return err
}

const addUser = `-- name: AddUser :exec
INSERT OR IGNORE INTO users (email, name) VALUES (?, ?)
`

type AddUserParams struct {
	Email string
	Name  string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser, arg.Email, arg.Name)
	return err
}

const cleanSessions = `-- name: CleanSessions :exec
DELETE FROM sessions WHERE
expires_at < strftime('%s', 'now')
`

func (q *Queries) CleanSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanSessions)
	return err
}

const closeBallot = `-- name: CloseBallot :exec
UPDATE ballots SET status = 'closed' WHERE id = ?
`

func (q *Queries) CloseBallot(ctx context.Context, id interface{}) error {
	_, err := q.db.ExecContext(ctx, closeBallot, id)
	return err
}

const completeBallot = `-- name: CompleteBallot :exec
UPDATE ballots SET status = 'complete' WHERE id = ?
`

func (q *Queries) CompleteBallot(ctx context.Context, id interface{}) error {
	_, err := q.db.ExecContext(ctx, completeBallot, id)
	return err
}

const countRemaining = `-- name: CountRemaining :one
SELECT COUNT(*) FROM ballot_candidates
WHERE ballot_id = ? AND eliminated = FALSE
`

func (q *Queries) CountRemaining(ctx context.Context, ballotID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRemaining, ballotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBallot = `-- name: CreateBallot :exec
INSERT INTO ballots (id, name, description) VALUES (?, ?, ?)
`

type CreateBallotParams struct {
	ID          interface{}
	Name        string
	Description string
}

func (q *Queries) CreateBallot(ctx context.Context, arg CreateBallotParams) error {
	_, err := q.db.ExecContext(ctx, createBallot, arg.ID, arg.Name, arg.Description)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
	id, user, expires_at
) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	User      string
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.User, arg.ExpiresAt)
	return err
}

const deleteVotes = `-- name: DeleteVotes :exec
DELETE FROM votes WHERE email = ? AND ballot_id = ?
`

type DeleteVotesParams struct {
	Email    string
	BallotID uuid.UUID
}

func (q *Queries) DeleteVotes(ctx context.Context, arg DeleteVotesParams) error {
	_, err := q.db.ExecContext(ctx, deleteVotes, arg.Email, arg.BallotID)
	return err
}

const eliminateCandidateBallot = `-- name: EliminateCandidateBallot :exec
UPDATE ballot_candidates
SET eliminated = TRUE
WHERE ballot_id = ? AND candidate_id = ?
`

type EliminateCandidateBallotParams struct {
	BallotID    uuid.UUID
	CandidateID uuid.UUID
}

func (q *Queries) EliminateCandidateBallot(ctx context.Context, arg EliminateCandidateBallotParams) error {
	_, err := q.db.ExecContext(ctx, eliminateCandidateBallot, arg.BallotID, arg.CandidateID)
	return err
}

const eliminateCandidateGlobally = `-- name: EliminateCandidateGlobally :exec
UPDATE ballot_candidates
SET eliminated = TRUE
WHERE candidate_id = ?
`

func (q *Queries) EliminateCandidateGlobally(ctx context.Context, candidateID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, eliminateCandidateGlobally, candidateID)
	return err
}

const getBallotCandidates = `-- name: GetBallotCandidates :many
SELECT c.id, c.name
FROM candidates c
JOIN ballot_candidates bc ON bc.candidate_id = c.id
WHERE bc.ballot_id = ? AND bc.eliminated = FALSE
ORDER BY c.name
`

func (q *Queries) GetBallotCandidates(ctx context.Context, ballotID uuid.UUID) ([]Candidate, error) {
	rows, err := q.db.QueryContext(ctx, getBallotCandidates, ballotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candidate
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBallotName = `-- name: GetBallotName :one
SELECT name FROM ballots WHERE id = ?
`

func (q *Queries) GetBallotName(ctx context.Context, id interface{}) (string, error) {
	row := q.db.QueryRowContext(ctx, getBallotName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getBallotStatus = `-- name: GetBallotStatus :one
SELECT status FROM ballots WHERE id = ?
`

func (q *Queries) GetBallotStatus(ctx context.Context, id interface{}) (string, error) {
	row := q.db.QueryRowContext(ctx, getBallotStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getBallotWinner = `-- name: GetBallotWinner :one
SELECT c.id, c.name
FROM candidates c
JOIN ballot_candidates bc ON bc.candidate_id = c.id
WHERE bc.ballot_id = ? AND bc.eliminated = FALSE
LIMIT 1
`

func (q *Queries) GetBallotWinner(ctx context.Context, ballotID uuid.UUID) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getBallotWinner, ballotID)
	var i Candidate
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCandidateName = `-- name: GetCandidateName :one
SELECT name FROM candidates WHERE id = ?
`

func (q *Queries) GetCandidateName(ctx context.Context, id interface{}) (string, error) {
	row := q.db.QueryRowContext(ctx, getCandidateName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getLastCandidate = `-- name: GetLastCandidate :one
SELECT candidate_id FROM ballot_candidates WHERE ballot_id = ? AND eliminated = FALSE LIMIT 1
`

func (q *Queries) GetLastCandidate(ctx context.Context, ballotID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getLastCandidate, ballotID)
	var candidate_id uuid.UUID
	err := row.Scan(&candidate_id)
	return candidate_id, err
}

const getSession = `-- name: GetSession :one
SELECT user
FROM sessions
WHERE id = ? AND
	  expires_at > strftime('%s', 'now')
`

func (q *Queries) GetSession(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var user string
	err := row.Scan(&user)
	return user, err
}

const hasVoted = `-- name: HasVoted :one

SELECT EXISTS (SELECT 1 FROM votes WHERE email = ? AND ballot_id = ?) AS has_voted
`

type HasVotedParams struct {
	Email    string
	BallotID uuid.UUID
}

// VOTING
func (q *Queries) HasVoted(ctx context.Context, arg HasVotedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasVoted, arg.Email, arg.BallotID)
	var has_voted bool
	err := row.Scan(&has_voted)
	return has_voted, err
}

const insertRankedVote = `-- name: InsertRankedVote :exec
INSERT INTO votes (email, ballot_id, candidate_id, rank)
VALUES (?, ?, ?, ?)
`

type InsertRankedVoteParams struct {
	Email       string
	BallotID    uuid.UUID
	CandidateID uuid.UUID
	Rank        int64
}

func (q *Queries) InsertRankedVote(ctx context.Context, arg InsertRankedVoteParams) error {
	_, err := q.db.ExecContext(ctx, insertRankedVote,
		arg.Email,
		arg.BallotID,
		arg.CandidateID,
		arg.Rank,
	)
	return err
}

const openBallot = `-- name: OpenBallot :exec
UPDATE ballots SET status = 'open' WHERE id = ?
`

func (q *Queries) OpenBallot(ctx context.Context, id interface{}) error {
	_, err := q.db.ExecContext(ctx, openBallot, id)
	return err
}

const userExists = `-- name: UserExists :one
SELECT 1 FROM users
WHERE email = ?
`

func (q *Queries) UserExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
